---
- hosts: all
  pre_tasks:
    - name: Load DB variables
      include_vars: '{{ pulp_db_type }}.yml'
  vars:
    pulp_default_admin_password: admin
    pulp_source_dir: '/home/travis/build/pulp/pulpcore/'
    pulp_plugin_source_dir: "/home/travis/build/pulp/pulpcore-plugin"
    pulp_install_plugins:
      pulp-rpm:
        app_label: "rpm"
        source_dir: "$TRAVIS_BUILD_DIR"
    ansible_python_interpreter: '/opt/pyenv/shims/python3'
    pulp_user: 'travis'
    developer_user: 'travis'
    pulp_install_db: false
    pulp_preq_packages: []
    pulp_settings:
      content_host: 'localhost:24816'
      secret_key: 'secret'
      databases:
        default:
          ENGINE: "{{ pulp_db_backend }}"
          USER: 'travis'
          PASSWORD: ''
  environment:
    DJANGO_SETTINGS_MODULE: pulpcore.app.settings
  roles:
    - pulp.pulp_rpm_prerequisites
    - pulp-database
    - pulp-workers
    - pulp-resource-manager
    - pulp-webserver
    - pulp-content
